version: "3"
services:
    mysql:
        image: mysql:8
        ports:
            - "${DB_PORT}:3306"
        user: '${OWNER_USER_ID}:${OWNER_GROUP_ID}'
        volumes:
            - mysql_db:/var/lib/mysql:delegated
            - ./docker/mysql/conf.d:/etc/mysql/conf.d
            - ./docker/mysql/log:/var/log/mysql
            - ./database/migrations:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
volumes:
    mysql_db:
        driver: local
